list: $/gemfourmedia/gcontent/models/item/columns.yaml
modelClass: GemFourMedia\GContent\Models\Item
title: Item
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcontent/item/update/:id'
filter: config_filter.yaml
