list: $/gemfourmedia/gcontent/models/group/columns.yaml
modelClass: GemFourMedia\GContent\Models\Group
title: Group
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcontent/group/update/:id'
