list: $/gemfourmedia/gcontent/models/serie/columns.yaml
modelClass: GemFourMedia\GContent\Models\Serie
title: Serie
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcontent/serie/update/:id'
