plugin:
    name: 'gemfourmedia.gcontent::lang.plugin.name'
    description: 'gemfourmedia.gcontent::lang.plugin.description'
    author: GemFourMedia
    icon: oc-icon-adjust
    homepage: 'https://wintercms.gemfourmedia.com/plugin/gcontent'
permissions:
    gcontent.access:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.access'
    gcontent.access_setting:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.access_setting'
    gcontent.group.manage:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.group.manage'
    gcontent.group.create:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.group.create'
    gcontent.group.update:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.group.update'
    gcontent.group.delete:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.group.delete'
    gcontent.item.manage:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.item.manage'
    gcontent.item.create:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.item.create'
    gcontent.item.update:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.item.update'
    gcontent.item.delete:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.item.delete'
    gcontent.category.manage:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.category.manage'
    gcontent.category.create:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.category.create'
    gcontent.category.update:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.category.update'
    gcontent.category.delete:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.category.delete'
    gcontent.serie.manage:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.serie.manage'
    gcontent.serie.create:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.serie.create'
    gcontent.serie.update:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.serie.update'
    gcontent.serie.delete:
        tab: 'gemfourmedia.gcontent::lang.plugin.name'
        label: 'gemfourmedia.gcontent::lang.permissions.serie.delete'
navigation:
    gcontent-main-menu:
        label: 'gemfourmedia.gcontent::lang.plugin.name'
        url: gemfourmedia/gcontent/item
        icon: icon-text-height
        permissions:
            - gcontent.access
        sideMenu:
            gcontent-menu-item:
                label: 'gemfourmedia.gcontent::lang.features.item'
                url: gemfourmedia/gcontent/item
                icon: icon-file-text
                permissions:
                    - gcontent.item.manage
            gcontent-menu-group:
                label: 'gemfourmedia.gcontent::lang.features.groups'
                url: gemfourmedia/gcontent/group
                icon: icon-tasks
                permissions:
                    - gcontent.group.manage
            gcontent-menu-category:
                label: 'gemfourmedia.gcontent::lang.features.category'
                url: gemfourmedia/gcontent/category
                icon: icon-sitemap
                permissions:
                    - gcontent.category.manage
            gcontent-menu-serie:
                label: 'gemfourmedia.gcontent::lang.features.serie'
                url: gemfourmedia/gcontent/serie
                icon: icon-newspaper-o
                permissions:
                    - gcontent.serie.manage
